###
GET http://localhost:3000/contacts/1

###
GET http://localhost:3000/contacts

###
POST http://localhost:3000/contacts
content-type: application/json

{
  "first_name": "John",
  "last_name": "Doe",
  "email": "jdoe@gmail.com",
  "phone_number": "432-786-9987",
  "address": "2001 Blake St, Denver, CO 80205"
}
###
PATCH http://localhost:3000/contacts/5
content-type: application/json

{
  "address": "Denver"
}

###
DELETE http://localhost:3000/contacts/5